# Generated by Django 3.2 on 2021-05-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_cart_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='qrcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
