# Generated by Django 3.2 on 2021-05-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_customer_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
