# Generated by Django 4.1.1 on 2022-09-22 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_items'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
    ]
