# Generated by Django 4.1.1 on 2022-09-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_sub_category_items_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='discount_price',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
